[package]
name = "open_recipe_format"
version = "0.1.0"
authors = ["Noël Martignoni <noel.martignoni@easymov.fr>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
anyhow = "1.0.26"
